name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Packages
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Check if @alexaegis/reactive-minesweeper-engine is already deployed
        run: |
          VERSION=$(cat ".github/version.txt")
          echo "::set-env name=VERSION::$VERSION"
          MINEENGINE_IS_ON_NPM=$(if [ ! -z "$(npm view @alexaegis/reactive-minesweeper-engine@$VERSION 2> /dev/null)" ]; then echo 'true'; else echo 'false'; fi)
          echo "::set-env name=MINEENGINE_IS_ON_NPM::$MINEENGINE_IS_ON_NPM"
          echo "$VERSION"
          echo "$MINEENGINE_IS_ON_NPM"
      - name: Check if @alexaegis/ng-minesweeper is already deployed
        run: |
          VERSION=$(cat ".github/version.txt")
          echo "::set-env name=VERSION::$VERSION"
          NGMINE_IS_ON_NPM=$(if [ ! -z "$(npm view @alexaegis/ng-minesweeper@$VERSION 2> /dev/null)" ]; then echo 'true'; else echo 'false'; fi)
          echo "::set-env name=NGMINE_IS_ON_NPM::$NGMINE_IS_ON_NPM"
          echo "$VERSION"
          echo "$NGMINE_IS_ON_NPM"
      - name: Install dependencies
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Build Typedocs
        if: env.NGMINE_IS_ON_NPM != 'true'
        run: yarn typedoc
      - name: Release @alexaegis/reactive-minesweeper-engine on NPM
        if: env.MINEENGINE_IS_ON_NPM != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish ./dist/libs/reactive-minesweeper-engine --access public
      - name: Release @alexaegis/ng-minesweeper on NPM
        if: env.NGMINE_IS_ON_NPM != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish ./dist/libs/ng-minesweeper --access public
      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/minesweeper
